services:
  data-load:
    networks:
      - app
    build:
      context: ..
      dockerfile: src/data_load/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - data:/app/data
    environment:
      - OUTPUT_PATH=/app/data/raw/petitions.csv
      - DB_PATH=/app/data/petitions.db

  data-quality:
    networks:
      - app
    build:
      context: ..
      dockerfile: src/data_quality_analysis/Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - data:/app/data
    environment:
      - DATA_RAW_PATH=/app/data/raw/petitions.csv

  data-research:
    networks:
      - app
    build:
      context: ..
      dockerfile: src/data_research/Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - data:/app/data
    environment:
      - DATA_RAW_PATH=/app/data/raw/petitions.csv

  visualization:
    networks:
      - app
    build:
      context: ..
      dockerfile: src/visualization/Dockerfile
    ports:
      - "8004:8000"
    volumes:
      - data:/app/data
      - reports:/app/reports
    environment:
      - DATA_RAW_PATH=/app/data/raw/petitions.csv
      - REPORTS_FIGURES_PATH=/app/reports/figures

  web:
    networks:
      - app
    build:
      context: ..
      dockerfile: src/web/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - data:/app/data
    depends_on:
      - data-load
      - data-quality
      - data-research
      - visualization
    environment:
      - DB_PATH=/app/data/petitions.db
      - DATA_LOAD_URL=http://data-load:8000
      - QUALITY_URL=http://data-quality:8000
      - RESEARCH_URL=http://data-research:8000
      - VIZ_URL=http://visualization:8000

  prometheus:
    image: prom/prometheus:v2.54.1
    networks:
      - app
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - web
      - node-exporter
      - cadvisor

  grafana:
    image: grafana/grafana-oss:11.2.0
    networks:
      - app
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.8.2
    networks:
      - app
    command:
      - "--path.rootfs=/host"
    volumes:
      - /:/host:ro,rslave

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    networks:
      - app
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  app:
    driver: bridge

volumes:
  data:
  reports:
  prometheus-data:
  grafana-data:
