apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-quality
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-quality
  template:
    metadata:
      labels:
        app: data-quality
    spec:
      containers:
        - name: data-quality
          image: data-quality:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATA_RAW_PATH
              value: /app/data/raw/petitions.csv
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          hostPath:
            path: /opt/app-data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: data-quality
  namespace: default
spec:
  selector:
    app: data-quality
  ports:
    - port: 8000
      targetPort: 8000
