apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.8.2
          args:
            - "--path.rootfs=/host"
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: rootfs
              mountPath: /host
              mountPropagation: HostToContainer
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: default
spec:
  selector:
    app: node-exporter
  ports:
    - port: 9100
      targetPort: 9100
