name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      module:
        description: "Specify module to run (optional)"
        required: false
        default: ""

jobs:
  prepare_data:
    name: Prepare data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create data directory
        run: mkdir -p data/raw

      - name: Download dataset
        run: |
          wget "https://data.gov.ua/dataset/dbfff194-ca0c-47e8-9434-6670236894a1/resource/2af4e39b-d6a3-4c1c-a5a8-f25597326f4d/download/petitions.csv" -O data/raw/petitions.csv

      - name: Upload raw data CSV
        uses: actions/upload-artifact@v4
        with:
          name: petitions-csv
          path: data/raw/petitions.csv

  data_load:
    name: Run data_load
    needs: prepare_data
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.module == '' || github.event.inputs.module == 'data_load' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download CSV
        uses: actions/download-artifact@v4
        with:
          name: petitions-csv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data_load
        run: python -m src.pipelines.data_load data/raw/petitions.csv

      - name: Upload data_load CSVs and logs
        uses: actions/upload-artifact@v4
        with:
          name: data_load-files
          path: |
            data_load_output/*.csv
            data_load_output/*.log

  data_quality_analysis:
    name: data_quality_analysis
    needs: prepare_data
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.module == '' || github.event.inputs.module == 'data_quality_analysis' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download CSV
        uses: actions/download-artifact@v4
        with:
          name: petitions-csv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data_quality_analysis
        run: python -m src.pipelines.data_quality_analysis data/raw/petitions.csv

      - name: Upload quality CSVs and logs
        uses: actions/upload-artifact@v4
        with:
          name: quality-files
          path: |
            quality_output/*.csv
            quality_output/*.log

  data_research:
    name: data_research
    needs: prepare_data
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.module == '' || github.event.inputs.module == 'data_research' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download CSV
        uses: actions/download-artifact@v4
        with:
          name: petitions-csv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data_research
        run: python -m src.pipelines.data_research data/raw/petitions.csv

      - name: Upload research CSVs and logs
        uses: actions/upload-artifact@v4
        with:
          name: research-files
          path: |
            research_output/*.csv
            research_output/*.log

  visualization:
    name: visualization
    needs: prepare_data
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.module == '' || github.event.inputs.module == 'visualization' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download CSV
        uses: actions/download-artifact@v4
        with:
          name: petitions-csv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run visualization
        run: python -m src.pipelines.visualization data/raw/petitions.csv

      - name: Upload plots and logs
        uses: actions/upload-artifact@v4
        with:
          name: visualization-files
          path: |
            visualization_output/*.png
            visualization_output/*.csv
            visualization_output/*.log
